// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NmqDay09LabCF.Models;

#nullable disable

namespace NmqDay09LabCF.Migrations
{
    [DbContext(typeof(NmqDay09LabCFContext))]
    [Migration("20251017111558_V1")]
    partial class V1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NmqDay09LabCF.Models.NmqLoai_San_Pham", b =>
                {
                    b.Property<long>("nmqId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("nmqId"));

                    b.Property<string>("nmqMaLoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("nmqTenLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("nmqTrangThai")
                        .HasColumnType("bit");

                    b.HasKey("nmqId");

                    b.ToTable("NmqLoai_San_Pham");
                });

            modelBuilder.Entity("NmqDay09LabCF.Models.NmqSan_Pham", b =>
                {
                    b.Property<long>("nmqId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("nmqId"));

                    b.Property<long>("NmqLoai_San_PhamnmqId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("nmqDonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("nmqHinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("nmqMaLoai")
                        .HasColumnType("bigint");

                    b.Property<string>("nmqMaSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nmqSoLuong")
                        .HasColumnType("int");

                    b.Property<string>("nmqTenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("nmqTrangThai")
                        .HasColumnType("bit");

                    b.HasKey("nmqId");

                    b.HasIndex("NmqLoai_San_PhamnmqId");

                    b.ToTable("NmqSan_Pham");
                });

            modelBuilder.Entity("NmqDay09LabCF.Models.NmqSan_Pham", b =>
                {
                    b.HasOne("NmqDay09LabCF.Models.NmqLoai_San_Pham", "NmqLoai_San_Pham")
                        .WithMany("nmqSan_Phams")
                        .HasForeignKey("NmqLoai_San_PhamnmqId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NmqLoai_San_Pham");
                });

            modelBuilder.Entity("NmqDay09LabCF.Models.NmqLoai_San_Pham", b =>
                {
                    b.Navigation("nmqSan_Phams");
                });
#pragma warning restore 612, 618
        }
    }
}
